"""
Storybook.ai - Google Image Engine
Uses Google's Gemini / Imagen 3 models for high-quality character generation.
"Nano-Banana" implementation.
"""

import asyncio
from dataclasses import dataclass
from typing import Optional
import google.generativeai as genai
from PIL import Image
import io
import aiohttp

from app.config import Settings
from app.engines.character_analyzer import CharacterTraits


@dataclass
class GoogleImage:
    """An image generated by Google's models."""
    image_data: bytes
    mime_type: str = "image/png"


class GoogleImageEngine:
    """
    Generates images using Google's Generative AI (Imagen 3).
    """

    MODEL_NAME = "imagen-3.0-generate-001" 

    def __init__(self, settings: Settings):
        self.settings = settings
        if not settings.gemini_api_key:
            print("⚠️ Warning: GEMINI_API_KEY not found in settings!")
        
        genai.configure(api_key=settings.gemini_api_key)
        # We might need to access the model specifically via the API if not available in standard SDK yet.
        # But for now, we assume standard generation.

    async def generate_character_sheet(
        self,
        prompt: str,
        negative_prompt: Optional[str] = None,
        aspect_ratio: str = "1:1",
    ) -> Optional[bytes]:
        """
        Generate a character sheet using Imagen 3.
        Note: The Python SDK for Imagen might differ slightly from Gemini text.
        We will use the rest API via aiohttp if SDK support is limited for Imagen 3 specifically,
        or the model.generate_images() method if available.
        """
        print(f"🍌 Nano-Banana (Imagen 3) generating: {prompt[:50]}...")

        # Since the SDK is rapidly evolving, we'll try the standard image generation method.
        # If that fails, we might need a fallback.
        
        # Wrapped in executor for async
        loop = asyncio.get_event_loop()
        try:
            return await loop.run_in_executor(None, self._generate_sync, prompt, negative_prompt)
        except Exception as e:
            print(f"❌ Google Image Generation failed: {e}")
            return None

    def _generate_sync(self, prompt: str, negative_prompt: str = None) -> Optional[bytes]:
        """Synchronous generation call."""
        # Using the standard genai.ImageGenerationModel if available
        try:
            # Attempt to list models to confirm availability (debugging)
            # for m in genai.list_models():
            #     if 'generateContent' in m.supported_generation_methods:
            #         print(m.name)
            
            # The specific class for Imagen in the new SDK is often accessing via specific model instantiation
            model = genai.ImageGenerationModel("imagen-3.0-generate-001")
            
            response = model.generate_images(
                prompt=prompt,
                number_of_images=1,
                aspect_ratio="1:1",
                safety_filter_level="block_only_high",
                person_generation="allow_adult", # Important for detailed characters? Check policy.
            )
            
            if response and response.images:
                # Return the bytes of the first image
                # The SDK usually creates PIL images or bytes
                image = response.images[0] 
                # Converting to bytes if it's a specific object
                # Check SDK docs: usually has .show() or .save(). 
                # It might have a .encoding or similar.
                
                # Assume standard PIL integration or property
                # If it wraps PIL:
                output = io.BytesIO()
                image.save(output, format="PNG")
                return output.getvalue()
                
            return None
            
        except Exception as e:
            print(f"❌ _generate_sync error: {e}")
            # Fallback to 'gemini-pro-vision' logic? No, that's for input.
            raise e

    def get_pixar_prompt(self, features: CharacterTraits) -> str:
        """
        Construct a prompt optimized for Imagen 3 ("Nano-Banana") to create a Pixar-style character sheet.
        """
        # Nano-Banana handles natural language very well.
        # We ask for a character sheet directly.
        
        return (
            f"Generate a professional 3D Pixar character design sheet for a child's movie. "
            f"Subject: {features.consistency_string}. "
            f"The image should contain 3 distinct poses arranged in a grid: "
            f"1. Front view, standing, neutral expression. "
            f"2. Side profile view. "
            f"3. Dynamic walking pose, happy. "
            f"Style: High-end 3D rendering, Disney/Pixar aesthetic, 8k resolution, subsurface scattering, expressive eyes. "
            f"Background: Clean white."
        )
